### ISSUE TITLE
v 3.3.0 launch/upcoming/ endpoint

### ISSUE THREAD

**Issue by MJRLegends** [ItsCalebJones/SpaceLaunchNow-Server#103]
endpoint: `https://spacelaunchnow.me/api/3.3.0/launch/upcoming/` seems to have launches that have passed in

**Comment by ItsCalebJones** [comment]
Yes, launches stay in /upcoming for 24 hours

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MJRLegends** [comment]
Ah ok fair enough
